apiVersion: v1
kind: Service
metadata:
  name: vehicle-risk-prediction
spec:
  type: LoadBalancer
  selector:
    app: vehicle-risk-prediction
  ports:
    - protocol: TCP
      port: 5005 # External port
      targetPort: 5005 # Container port
